name: Build and Push to GHCR

on:
  push:
    branches:
      - main 

env:
  REGISTRY: ghcr.io
  # 【核心修改点】直接写死全小写的用户名 lzy-lzy2025，并将项目名改为 876
  IMAGE_NAME: lzy-lzy2025/876

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
